-- MySQL Script generated by MySQL Workbench
-- Tue Jul 28 10:26:35 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema course_enrollment
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema course_enrollment
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `course_enrollment` DEFAULT CHARACTER SET utf8 ;
USE `course_enrollment` ;

-- -----------------------------------------------------
-- Table `course_enrollment`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `course_enrollment`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `role` ENUM('ADMIN', 'STUDENT') NOT NULL DEFAULT 'STUDENT',
  `nrp` VARCHAR(9) NULL,
  `max_credits` INT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `nrp_UNIQUE` (`nrp` ASC),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `course_enrollment`.`courses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `course_enrollment`.`courses` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `code` VARCHAR(8) NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `credits` INT NOT NULL DEFAULT 0,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC),
  UNIQUE INDEX `code_UNIQUE` (`code` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `course_enrollment`.`course_plans`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `course_enrollment`.`course_plans` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `student_id` INT NOT NULL,
  `status` ENUM('DRAFT', 'APPROVED', 'PARTIALLY_APPROVED', 'REJECTED', 'SUBMITTED') NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `fk_course_plans_users_idx` (`student_id` ASC),
  CONSTRAINT `fk_course_plans_users`
    FOREIGN KEY (`student_id`)
    REFERENCES `course_enrollment`.`users` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `course_enrollment`.`course_plans_items`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `course_enrollment`.`course_plans_items` (
  `course_plan_id` INT NOT NULL,
  `course_id` INT NOT NULL,
  `status` ENUM('PENDING', 'APPROVED', 'REJECTED') NOT NULL DEFAULT 'PENDING',
  `remarks` TEXT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`course_plan_id`, `course_id`),
  INDEX `fk_course_plans_has_courses_courses1_idx` (`course_id` ASC),
  INDEX `fk_course_plans_has_courses_course_plans1_idx` (`course_plan_id` ASC),
  CONSTRAINT `fk_course_plans_has_courses_course_plans1`
    FOREIGN KEY (`course_plan_id`)
    REFERENCES `course_enrollment`.`course_plans` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_course_plans_has_courses_courses1`
    FOREIGN KEY (`course_id`)
    REFERENCES `course_enrollment`.`courses` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
